-- MySQL Script generated by MySQL Workbench
-- mar. 15 févr. 2022 15:30:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mangaverse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mangaverse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mangaverse` ;
USE `mangaverse` ;

-- -----------------------------------------------------
-- Table `mangaverse`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangaverse`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `biography` LONGTEXT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `isAdmin` INT(1) NOT NULL DEFAULT 0,
  `isBan` INT(1) NOT NULL DEFAULT 0,
  `isVerified` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`mail` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mangaverse`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangaverse`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mangaverse`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangaverse`.`articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `genre_2` VARCHAR(45) NULL,
  `genre_1` VARCHAR(45) NULL,
  `synopsis` LONGTEXT NULL,
  `img` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  INDEX `fk_articles_user_idx` (`author_id` ASC) VISIBLE,
  UNIQUE INDEX `img_UNIQUE` (`img` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_articles_user`
    FOREIGN KEY (`author_id`)
    REFERENCES `mangaverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mangaverse`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangaverse`.`sessions` (
  `session_id` INT NOT NULL,
  `expires` VARCHAR(255) NOT NULL,
  `data` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`session_id`),
  UNIQUE INDEX `data_UNIQUE` (`data` ASC) VISIBLE,
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mangaverse`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangaverse`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `article_id` INT NOT NULL,
  INDEX `fk_comments_users1_idx` (`author_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_comments_articles1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`author_id`)
    REFERENCES `mangaverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`article_id`)
    REFERENCES `mangaverse`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mangaverse`.`tomes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mangaverse`.`tomes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `articles_id` INT NOT NULL,
  `number` INT NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tomes_articles1_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `fk_tomes_articles1`
    FOREIGN KEY (`name`)
    REFERENCES `mangaverse`.`articles` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
